✨ parse data.gov.tw csv to json
taiwan-voting-guide/data-pipeline pull request #11
Opened 2023-02-11 09:15 UTC by iml885203

2023-02-11 09:33 UTC, bangyuwen commented
資料相關
1. 移動下載檔案路徑到 './data'
2. 生日格式改為 1992-01-01
3. 資料 denormalize
4. 移除不明空格

2023-02-13 14:55 UTC, bangyuwen requested changes
Hierarchy of code should be cleaner

2023-02-13 14:55 UTC, bangyuwen commented on cmd/data_gov_tw/main.go
> +	renameFile("2016總統立委/區域立委/elcand_T1.csv", "2016總統立委/區域立委/elcand.csv")
extract to something like

```
fixFilename()
```

2023-02-13 14:55 UTC, bangyuwen commented on cmd/data_gov_tw/main.go
> +	loadFirstFolders()
Rename function, since it not only loads folders.

2023-02-13 14:55 UTC, bangyuwen commented on cmd/data_gov_tw/main.go
> +func readCSVToMap(filepath string, columnsMapper []string) ([]map[string]string, error) {
https://github.com/go-gota/gota

Have you considered to use `dataframe.ReadCSV` ?

2023-02-13 14:55 UTC, bangyuwen commented on cmd/data_gov_tw/main.go
> +// 政黨欄位對應
Comment's lang. should be consistent

2023-02-14 00:10 UTC, iml885203 commented on cmd/data_gov_tw/main.go
> +func readCSVToMap(filepath string, columnsMapper []string) ([]map[string]string, error) {
對這套件還不熟悉，想說直接寫比較快  
目前是遇到 CSV 第一行不是 title，不直接用 `dataframe.ReadCSV`

2023-02-15 13:28 UTC, merged